### ISSUE TITLE
Problems when creating a table with [i][j] index from another [i][j] indexed table

### ISSUE THREAD

**Issue by SeraphL** [dimitrijejankov/simsql#1]
For example, assume we have two tables a[i][j] and d[i][j] defined as follows:

create table a[0][0](dataID, e) as 
    select b.dataID, b.x
    from b;

create table a[i:0...][j:1...](dataID, e) as
    select aa.dataID as dataID, (aa.e - b.x) as e
    from a[i][j-1] as aa, b as bb;

create table d[i:0...][j:1...](dataID, e) as
    select aa.dataID as dataID, aa.e as e
    from a[i][j] as aa;

Then when we define another table from d:

create table c[i:0...][j:1...](dataID, e) as
    select aa.dataID as dataID, aa.e as e
    from d[i][j] as aa;

There will be an error reported:

selected attribute [aa.dataid] is not found in any relation!
java.lang.Exception: selected attribute [dataid] is not found in any relation!
	at simsql.compiler.TypeChecker.visitColumnExpression(TypeChecker.java:1260)
	at simsql.compiler.ColumnExpression.acceptVisitor(ColumnExpression.java:73)
	at simsql.compiler.TypeChecker.visitDerivedColumn(TypeChecker.java:792)
	at simsql.compiler.DerivedColumn.acceptVisitor(DerivedColumn.java:53)
	at simsql.compiler.RandomTableTypeChecker.visitRandomTableStatement(RandomTableTypeChecker.java:317)
	at simsql.compiler.MultidimensionalTableTypeChecker.visitMultidimensionalTableStatement(MultidimensionalTableTypeChecker.java:16)
	at simsql.compiler.CompilerProcessor.typeCheck(CompilerProcessor.java:164)
	at simsql.compiler.SimsqlCompiler.parseString(SimsqlCompiler.java:115)
	at simsql.compiler.SimsqlCompiler.parseString(SimsqlCompiler.java:45)
	at simsql.shell.kernel.SimSQLShell.parseLine(SimSQLShell.java:432)
	at simsql.shell.kernel.SimSQLShell.promptLoop(SimSQLShell.java:379)
	at simsql.shell.kernel.MainClass.main(MainClass.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Error parsing query:java.lang.Exception: selected attribute [dataid] is not found in any relation!; while parsing

**Comment by SeraphL** [comment]
Not a problem from the system side.
