### ISSUE TITLE
The system reports errors when the iterations are bigger than 10 in feedforward backpropagation nn

### ISSUE THREAD

**Issue by SeraphL** [dimitrijejankov/simsql#5]
For the feedforward backpropagation nn (see previous emails), when I ran

select * from activation[10][2]

the system reported this error:

Monte Carlo iteration 9/10

Invoking the optimizer...

Executing the plan. Number of operations to go is...

30->29->28->27->26->25->24 (running Selection as Hadoop job...)

23->22 (running Selection as Hadoop job...)

21 (running Aggregate as Hadoop job...)

20->19 (running Selection as Hadoop job...)

18 (running Aggregate as Hadoop job...)

17 (running Selection as Hadoop job...)

16 (running Aggregate as Hadoop job...)

15->14 (running Selection as Hadoop job...)

13 (running Aggregate as Hadoop job...)

12 (running Selection as Hadoop job...)

11 (running Aggregate as Hadoop job...)

10 (running Join as Hadoop job...)

9 (running Selection as Hadoop job...)

8 (running Join as Hadoop job...)

7->6->5 (running Aggregate as Hadoop job...)

4 (running Join as Hadoop job...)

3 (running Selection as Hadoop job...)

2 (running Aggregate as Hadoop job...)

1 (running FrameOutput as Hadoop job...)

java.lang.StringIndexOutOfBoundsException: String index out of range: -1

at java.lang.String.substring(String.java:1911)

at simsql.compiler.MultidimensionalTableSchema.getBracketsTableNameFromQualifiedTableName(MultidimensionalTableSchema.java:65)

at simsql.compiler.PlanInstantiation.findMatchingGeneralIndexTable(PlanInstantiation.java:300)

at simsql.compiler.PlanInstantiation.generatePlan(PlanInstantiation.java:108)

at simsql.shell.query_processor.MCMCQueryProcessor.generatePlan(MCMCQueryProcessor.java:325)

at simsql.shell.query_processor.MCMCQueryProcessor.nextIteration(MCMCQueryProcessor.java:240)

at simsql.shell.query_processor.MCMCQueryProcessor.nextIteration(MCMCQueryProcessor.java:43)

at simsql.shell.kernel.SimSQLShell.execute(SimSQLShell.java:947)

at simsql.shell.kernel.SimSQLShell.parseLine(SimSQLShell.java:463)

at simsql.shell.kernel.SimSQLShell.promptLoop(SimSQLShell.java:379)

at simsql.shell.kernel.MainClass.main(MainClass.java:40)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:606)

at org.apache.hadoop.util.RunJar.run(RunJar.java:221)

at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

ERROR!

java.lang.RuntimeException: exception happens in generatePlan

at simsql.shell.query_processor.MCMCQueryProcessor.generatePlan(MCMCQueryProcessor.java:362)

at simsql.shell.query_processor.MCMCQueryProcessor.nextIteration(MCMCQueryProcessor.java:240)

at simsql.shell.query_processor.MCMCQueryProcessor.nextIteration(MCMCQueryProcessor.java:43)

at simsql.shell.kernel.SimSQLShell.execute(SimSQLShell.java:947)

**Comment by SeraphL** [comment]
Solved in the latest release.
